name: "Merkle API CI"

env:
  PACKAGE_NAME: "@sablier/v2-merkle-api"
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  pull_request:
    branches:
      - "main"
  workflow_call:
  workflow_dispatch:

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Setup: checkout the repo"
        uses: "actions/checkout@v3"

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: "Vercel: pull environment"
        run:  "npx vercel pull --environment=production --token=$VERCEL_TOKEN --yes"

      # Set up Rust
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Navigate to Rust project directory and build
      - name: Build Rust API
        run: |
          cd ./merkle-api
          cargo build --release
