name: "CI"

on:
  # Any pull request activity (open, synchronize, reopen)
  pull_request:
  # When called from another workflow
  workflow_call:

jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"

      - uses: "dtolnay/rust-toolchain@nightly"
        with:
          components: "clippy,rustfmt"

      - uses: "Swatinem/rust-cache@v2"
        with:
          shared-key: "musl"

      - name: "Rustfmt"
        run: "cargo +nightly fmt --all -- --check"

      - name: "Clippy"
        run: "cargo +nightly clippy --all-targets -- -D warnings"
