name: "Deploy on Vercel"

# Allow only one concurrent deployment, canceling runs queued between the run in-progress and latest queued
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  # Can be manually triggered by any member with Write permission
  workflow_dispatch:

jobs:
  deploy:
    environment: "Production"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Rust with the musl target"
        uses: "moonrepo/setup-rust@v1"
        with:
          targets: "x86_64-unknown-linux-musl"

      - name: "Install musl-tools to provide musl-gcc"
        uses: "awalsh128/cache-apt-pkgs-action@v1"
        with:
          packages: "musl-tools"
          version: "1.0"

      # See https://github.com/vercel-community/rust/issues/134
      - name: "Add Cargo config file"
        run: |
          mkdir -p .cargo
          echo '[build]' > .cargo/config.toml
          echo 'target = "x86_64-unknown-linux-musl"' >> .cargo/config.toml

      - name: "Vercel: pull environment"
        run: "npx vercel pull --environment=production --token=$VERCEL_TOKEN --yes"

      - name: "Vercel: build project artifacts"
        run: "npx vercel build --prod --token=$VERCEL_TOKEN"

      - name: "Deploy to Vercel"
        run: "npx vercel deploy --prod --prebuilt --token=$VERCEL_TOKEN"

      - name: "Add summary"
        run: |
          echo "## Deploy Vercel result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
