name: "Merkle API Deployment on Vercel"

env:
  PACKAGE_NAME: "@sablier/v2-merkle-api"
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  # push:
  #   branches:
  #     - "main"
  workflow_dispatch:

  # This probably requires a linux image to be created
  # Some experiments are still required re. prebuilt deployments (https://github.com/vercel-community/rust#prebuilt-deployments)

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Setup: checkout the repo"
        uses: "actions/checkout@v3"

      - name: Install Rust target
        run: |
          sudo apt update
          sudo apt install musl-tools
          rustup target add x86_64-unknown-linux-gnu

      - name: Install OpenSSL dependencies
        run: sudo apt-get install -y libssl-dev pkg-config

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: "Vercel: pull environment"
        run: "npx vercel pull --environment=production --token=$VERCEL_TOKEN --yes"

      - name: "Vercel: build project artifacts for ${{env.PACKAGE_NAME}}"
        run: "npx vercel build --prod --token=$VERCEL_TOKEN"

      - name: Deploy to Vercel
        run: "vercel deploy --prod --prebuilt --token=$VERCEL_TOKEN"
