name: "Deploy Merkle API on Vercel"

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  workflow_dispatch:

# This probably requires a Linux image to be created
# Some experiments are still required re. prebuilt deployments (https://github.com/vercel-community/rust#prebuilt-deployments)

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Rust target for Linux"
        run: "rustup target add x86_64-unknown-linux-gnu"

      - name: "Install Vercel CLI"
        run: "npm install --global vercel"

      - name: "Vercel: pull environment"
        run: "npx vercel pull --environment=production --token=$VERCEL_TOKEN --yes"

      - name: "Vercel: build project artifacts for v2-merkle-api"
        run: "npx vercel build --prod --token=$VERCEL_TOKEN"

      - name: "Deploy to Vercel"
        run: "vercel deploy --prod --prebuilt --token=$VERCEL_TOKEN"
